#!/usr/bin/env python3
"""
Telegram UltraPassive Recon Bot - Complete OSINT Intelligence Gathering
Windows Compatible - NO active scanning whatsoever
Only uses public data sources (no target contact)
"""

import asyncio
import json
import os
import re
import socket
import ssl
import sys
import time
import warnings
from datetime import datetime
from collections import defaultdict
from urllib.parse import urlparse, urljoin
from urllib3.exceptions import InsecureRequestWarning
warnings.filterwarnings('ignore', category=InsecureRequestWarning)

try:
    import requests
    from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
    from telegram.ext import (
        Application, CommandHandler, CallbackQueryHandler,
        MessageHandler, filters, ContextTypes,
    )
except ImportError:
    print("Missing python-telegram-bot. Install: pip install python-telegram-bot")
    sys.exit(1)

TELEGRAM_BOT_TOKEN = "8906545053:AAGXsBDmlPLasrjhzsnMc9oY17UvS6pt8b8"
YOUR_TELEGRAM_USER_ID = 8335028744 


def is_authorized(update):
    return update.effective_user.id == YOUR_TELEGRAM_USER_ID


def extract_title(html):
    match = re.search(r'<title[^>]*>(.*?)</title>', html, re.IGNORECASE | re.DOTALL)
    return match.group(1).strip() if match else "N/A"


async def send_long_message(chat_id, context, text, chunk_size=4000):
    lines = text.split('\n')
    chunks, current = [], ""
    for line in lines:
        if len(current) + len(line) + 1 > chunk_size:
            chunks.append(current)
            current = line
        else:
            current = (current + "\n" + line) if current else line
    if current:
        chunks.append(current)
    for chunk in chunks:
        try:
            await context.bot.send_message(chat_id, chunk)
            await asyncio.sleep(0.3)
        except:
            pass


# ======================== WAF DETECTION ========================

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cfduid"],
        "body": ["cloudflare", "checking your browser", "attention required!"],
        "cookies": ["__cfduid", "cf_clearance"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "akamai-cache-status"],
        "cookies": ["_abck", "bm_sz", "ak_bmsc"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "body": ["aws-waf", "request blocked"],
    },
    "CloudFront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop", "x-cache"],
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "x-cdn", "incapsula"],
        "body": ["incapsula"],
        "cookies": ["incap_ses", "visid_incap"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body": ["sucuri", "cloudproxy.sucuri.net"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-asm-version", "x-wa-ver", "x-waf"],
        "cookies": ["TS", "BIGipServer"],
    },
    "ModSecurity": {
        "headers": ["x-mod-security"],
        "body": ["modsecurity", "this error was generated by modsecurity"],
    },
    "Fortinet FortiWeb": {
        "headers": ["x-fw-debug", "x-fortinet"],
        "body": ["fortiweb"],
    },
    "Barracuda WAF": {
        "headers": ["x-barracuda"],
        "body": ["barracuda web application firewall"],
    },
    "Citrix NetScaler": {
        "headers": ["ns_client_ip", "x-ns-gateway"],
        "cookies": ["NSC_", "citrix_ns_id"],
    },
    "Radware WAF": {
        "headers": ["x-sdn"],
        "body": ["radware"],
    },
    "Wordfence": {
        "body": ["wordfence", "generated by wordfence"],
        "cookies": ["wfvt_", "wordfence_verifiedhuman"],
    },
    "Varnish Cache": {
        "headers": ["x-varnish", "x-cache"],
    },
    "Azure WAF": {
        "headers": ["x-ms-request-id", "x-azure-ref"],
        "body": ["azure application gateway"],
    },
    "Google Cloud Armor": {
        "headers": ["x-cloud-trace-context"],
        "body": ["cloud-armor"],
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "x-served-by", "x-timer"],
    },
    "StackPath": {
        "headers": ["x-stackpath-id"],
    },
    "BunnyCDN": {
        "headers": ["x-bunny"],
    },
    "KeyCDN": {
        "headers": ["x-keycdn"],
    },
    "LiteSpeed Cache": {
        "headers": ["x-litespeed-cache", "x-lsadc"],
        "body": ["litespeed"],
    },
    "Reblaze WAF": {
        "headers": ["x-reblaze"],
    },
}


def detect_waf(headers, body, cookies_str, status_code):
    detected = []
    body_lower = body.lower() if body else ""
    ch = {k.lower(): v.lower() for k, v in headers.items()}
    cl = cookies_str.lower() if cookies_str else ""
    
    for waf_name, sigs in WAF_SIGNATURES.items():
        score = 0
        reasons = []
        
        for h in sigs.get("headers", []):
            if h.lower() in ch:
                score += 2
                reasons.append(f"Header: {h}={ch[h.lower()][:50]}")
        for b in sigs.get("body", []):
            if b.lower() in body_lower:
                score += 3
                reasons.append(f"Body: {b}")
        for c in sigs.get("cookies", []):
            if c.lower() in cl:
                score += 3
                reasons.append(f"Cookie: {c}")
        
        if score >= 3:
            detected.append({
                "name": waf_name,
                "confidence": "HIGH" if score >= 5 else "MEDIUM",
                "reasons": reasons[:3],
                "score": score
            })
    
    detected.sort(key=lambda x: x["score"], reverse=True)
    return detected


# ======================== TECH DETECTION ========================

def detect_technologies(headers, body, cookies_str, target):
    bl = body.lower() if body else ""
    ch = {k.lower(): v for k, v in headers.items()}
    techs = []
    server = ch.get('server', '')
    x_power = ch.get('x-powered-by', '')
    
    # Web Servers
    if 'cloudflare' in server:
        techs.append(("Web Server", "Cloudflare (Reverse Proxy)", "HIGH"))
    elif re.search(r'nginx', server, re.I):
        v = re.search(r'nginx/([\d.]+)', server)
        techs.append(("Web Server", f"Nginx {v.group(1) if v else ''}", "HIGH"))
    elif re.search(r'apache', server, re.I):
        v = re.search(r'Apache/([\d.]+)', server, re.I)
        techs.append(("Web Server", f"Apache {v.group(1) if v else ''}", "HIGH"))
    elif re.search(r'iis', server, re.I):
        v = re.search(r'IIS/([\d.]+)', server, re.I)
        techs.append(("Web Server", f"IIS {v.group(1) if v else ''}", "HIGH"))
    elif re.search(r'openresty', server, re.I):
        techs.append(("Web Server", "OpenResty", "HIGH"))
    elif re.search(r'caddy', server, re.I):
        techs.append(("Web Server", "Caddy", "HIGH"))
    elif re.search(r'litespeed', server, re.I):
        techs.append(("Web Server", "LiteSpeed", "HIGH"))
    elif re.search(r'gws', server, re.I):
        techs.append(("Web Server", "Google Web Server", "HIGH"))
    elif re.search(r'amazon|awselb', server, re.I):
        techs.append(("Web Server", "AWS ELB", "HIGH"))
    elif re.search(r'varnish', server, re.I):
        techs.append(("Cache", "Varnish Cache", "HIGH"))
    
    # Backend Languages
    if 'php' in x_power:
        v = re.search(r'PHP/([\d.]+)', x_power)
        techs.append(("Backend", f"PHP {v.group(1) if v else ''}", "HIGH"))
    elif 'phpsessid' in cookies_str.lower():
        techs.append(("Backend", "PHP (session)", "HIGH"))
    if 'asp.net' in x_power:
        v = re.search(r'ASP\.NET[\s/]*([\d.]+)', x_power, re.I)
        techs.append(("Backend", f"ASP.NET {v.group(1) if v else ''}", "HIGH"))
    if 'x-aspnet-version' in ch:
        techs.append(("Backend", f"ASP.NET v{ch['x-aspnet-version']}", "HIGH"))
    if 'jsessionid' in cookies_str.lower():
        techs.append(("Backend", "Java (JSESSIONID)", "HIGH"))
    if 'x-application-context' in ch:
        techs.append(("Framework", "Spring Boot", "HIGH"))
    if 'csrftoken' in cookies_str.lower() or 'django_session' in cookies_str.lower():
        techs.append(("Backend", "Django (Python)", "HIGH"))
    if '_session_id' in cookies_str.lower() or 'x-rails' in ch:
        techs.append(("Backend", "Ruby on Rails", "HIGH"))
    if 'x-powered-by: express' in str(ch):
        techs.append(("Backend", "Express.js (Node)", "HIGH"))
    if 'x-gin' in ch:
        techs.append(("Backend", "Gin (Go)", "HIGH"))
    
    # CMS
    wp = 0
    for p in ['wp-content', 'wp-includes', 'wordpress', 'wp-json']:
        if p in bl: wp += 1
    if wp >= 2:
        v = re.search(r'wordpress\s+([\d.]+)', bl)
        techs.append(("CMS", f"WordPress {v.group(1) if v else ''}", "HIGH"))
        for t in list(set(re.findall(r'wp-content/themes/([^/]+)/', bl)))[:3]:
            techs.append(("WP Theme", t, "MEDIUM"))
        for p in list(set(re.findall(r'wp-content/plugins/([^/]+)/', bl)))[:8]:
            techs.append(("WP Plugin", p, "MEDIUM"))
    if 'joomla' in bl:
        techs.append(("CMS", "Joomla", "HIGH"))
    if 'drupal' in bl:
        techs.append(("CMS", "Drupal", "HIGH"))
    if 'magento' in bl or 'mage-cache' in bl:
        techs.append(("CMS", "Magento", "HIGH"))
    if 'shopify' in bl:
        techs.append(("CMS", "Shopify", "HIGH"))
    if 'squarespace' in bl:
        techs.append(("CMS", "Squarespace", "HIGH"))
    if 'wix' in bl:
        techs.append(("CMS", "Wix", "HIGH"))
    if 'umbraco' in bl:
        techs.append(("CMS", "Umbraco (.NET)", "HIGH"))
    
    # JavaScript Frameworks
    js_patterns = {
        "React": [r'react(?:\.development)?\.js', r'__NEXT_DATA__', r'react\.min\.js'],
        "Angular": [r'angular\.js', r'ng-version', r'ng-app'],
        "Vue.js": [r'vue\.js', r'__VUE__', r'v-bind', r'v-model'],
        "jQuery": [r'jquery[.-](\d)', r'jQuery', r'jquery\.min\.js'],
        "Bootstrap": [r'bootstrap\.min\.css', r'col-md-', r'col-lg-'],
        "Tailwind CSS": [r'tailwindcss', r'tailwind\.'],
        "Next.js": [r'__NEXT_DATA__', r'/_next/static'],
        "Nuxt.js": [r'__NUXT__', r'/_nuxt/'],
        "Alpine.js": [r'alpinejs', r'x-data', r'x-init'],
        "HTMX": [r'htmx\.org', r'hx-get', r'hx-post'],
        "D3.js": [r'd3\.js', r'd3\.min'],
        "Chart.js": [r'chart\.js', r'chart\.min'],
        "Leaflet": [r'leaflet\.js', r'L\.map'],
        "GSAP": [r'gsap', r'TweenMax'],
        "Three.js": [r'three\.js', r'THREE\.'],
    }
    for fw, patterns in js_patterns.items():
        for p in patterns:
            if re.search(p, bl):
                techs.append(("JS Framework", fw, "HIGH"))
                break
    
    # Analytics
    analytics = {
        "Google Analytics": [r'google-analytics\.com', r'ga\.js', r'gtag', r'G-[A-Z0-9]+'],
        "Google Tag Manager": [r'googletagmanager\.com', r'GTM-'],
        "Facebook Pixel": [r'facebook\.com/tr', r'fbq\('],
        "Hotjar": [r'hotjar', r'hj\('],
        "Mixpanel": [r'mixpanel', r'mxpnl'],
        "HubSpot": [r'js\.hs-scripts\.com', r'hubspot'],
        "Intercom": [r'intercom', r'widget\.intercom\.io'],
        "Zendesk": [r'zendesk', r'widget\.zendesk\.com'],
        "Cloudflare Analytics": [r'cloudflareinsights\.com'],
        "Matomo": [r'matomo\.js', r'piwik\.js'],
        "Yandex Metrica": [r'mc\.yandex\.ru', r'yandex_metrika'],
        "Microsoft Clarity": [r'clarity\.ms', r'microsoft\.com/clarity'],
        "LinkedIn Insight": [r'linkedin\.com/insight'],
        "TikTok Pixel": [r'tiktok\.com/analytics', r'_ttp'],
        "Pinterest Tag": [r'pinterest\.com/ct/'],
        "Reddit Pixel": [r'reddit\.com/static/pixel'],
        "Sentry": [r'@sentry', r'raven\.js'],
        "New Relic": [r'newrelic\.com', r'js-agent\.newrelic'],
        "FullStory": [r'fullstory\.com', r'fs\.com'],
        "Segment": [r'cdn\.segment\.com', r'segment\.com/analytics'],
        "Amplitude": [r'amplitude\.com', r'amplitude\.js'],
    }
    for svc, patterns in analytics.items():
        for p in patterns:
            if re.search(p, bl):
                techs.append(("Analytics", svc, "HIGH"))
                break
    
    # CDN
    cdns = {
        "Cloudflare CDN": [r'cdn\.cloudflare\.net'],
        "Akamai CDN": [r'akamaized\.net', r'\.akamai\.net'],
        "Fastly CDN": [r'fastly\.net', r'global\.ssl\.fastly'],
        "Amazon CloudFront": [r'cloudfront\.net'],
        "Amazon S3": [r's3\.amazonaws\.com', r's3-website'],
        "Google Cloud": [r'googleapis\.com', r'gstatic\.com'],
        "Azure CDN": [r'azureedge\.net', r'azurefd\.net'],
        "jsDelivr": [r'cdn\.jsdelivr\.net'],
        "cdnjs": [r'cdnjs\.cloudflare\.com'],
        "Unpkg": [r'unpkg\.com'],
        "BunnyCDN": [r'\.b-cdn\.net', r'bunnycdn'],
        "StackPath": [r'stackpathcdn\.com'],
        "KeyCDN": [r'\.kxcdn\.com'],
    }
    for cdn, patterns in cdns.items():
        for p in patterns:
            if re.search(p, bl):
                techs.append(("CDN", cdn, "HIGH"))
                break
    
    # Security Headers
    sec_headers = {
        'Strict-Transport-Security': 'HSTS',
        'Content-Security-Policy': 'CSP',
        'X-Frame-Options': 'X-Frame-Options',
        'X-Content-Type-Options': 'X-Content-Type-Options',
        'X-XSS-Protection': 'X-XSS-Protection',
        'Referrer-Policy': 'Referrer-Policy',
    }
    for hdr, label in sec_headers.items():
        if hdr.lower() in ch:
            techs.append(("Security", f"{label}: {ch[hdr.lower()][:60]}", "MEDIUM"))
    
    return techs


# ======================== CERTIFICATE INFO ========================

def get_certificate_info(hostname, port=443):
    try:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        with socket.create_connection((hostname, port), timeout=5) as sock:
            with ctx.wrap_socket(sock, server_hostname=hostname) as ssock:
                cert = ssock.getpeercert(binary_form=False)
                if not cert:
                    return None
                info = {}
                subject = dict(x[0] for x in cert.get('subject', []))
                info['cn'] = subject.get('commonName', 'N/A')
                info['org'] = subject.get('organizationName', 'N/A')
                info['country'] = subject.get('countryName', 'N/A')
                issuer = dict(x[0] for x in cert.get('issuer', []))
                info['issuer'] = issuer.get('commonName', 'N/A')
                info['valid_from'] = cert.get('notBefore', 'N/A')
                info['valid_to'] = cert.get('notAfter', 'N/A')
                sans = [ext[1] for ext in cert.get('subjectAltName', []) if ext[0] == 'DNS']
                info['sans'] = sans[:30]
                info['sans_count'] = len(sans)
                info['cipher'] = ssock.cipher()
                return info
    except:
        return None


# ======================== WHOIS SOCKET FALLBACK ========================

async def whois_socket_lookup(target, detailed=False):
    whois_servers = {
        'com': 'whois.verisign-grs.com', 'net': 'whois.verisign-grs.com',
        'org': 'whois.pir.org', 'info': 'whois.afilias.net',
        'io': 'whois.nic.io', 'co': 'whois.nic.co',
        'me': 'whois.nic.me', 'xyz': 'whois.nic.xyz',
        'dev': 'whois.nic.google', 'app': 'whois.nic.google',
        'uk': 'whois.nic.uk', 'de': 'whois.denic.de',
        'fr': 'whois.nic.fr', 'br': 'whois.registro.br',
        'ai': 'whois.nic.ai', 'tech': 'whois.nic.tech',
        'cloud': 'whois.nic.cloud', 'io': 'whois.nic.io',
    }
    tld = target.split('.')[-1]
    server = whois_servers.get(tld, 'whois.verisign-grs.com')
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(10)
        sock.connect((server, 43))
        sock.send((target + "\r\n").encode())
        resp = b""
        while True:
            d = sock.recv(4096)
            if not d:
                break
            resp += d
        sock.close()
        text = resp.decode('utf-8', errors='ignore')
        relevant = [l.strip() for l in text.split('\n') 
                    if any(x in l.lower() for x in ['registrar', 'creation date', 'expir', 'name server',
                                                     'org', 'country', 'admin email', 'registrant', 'dnssec',
                                                     'domain name', 'status:', 'dnssec'])]
        if relevant:
            return "=== [2] WHOIS ===\n" + "\n".join(f"  {l}" for l in relevant[:20])
        return "=== [2] WHOIS ===\n  No data returned from {server}"
    except Exception as e:
        return f"=== [2] WHOIS ===\n  Error: {str(e)}"


# ======================== MAIN RECON FUNCTION ========================

async def passive_recon(target, update, context):
    chat_id = update.effective_chat.id
    results = []
    start_time = datetime.now()
    
    results.append(f"ULTRA PASSIVE RECON REPORT")
    results.append(f"Target: {target}")
    results.append(f"Date: {start_time.strftime('%Y-%m-%d %H:%M:%S')}")
    results.append(f"{'='*60}")
    results.append("100% OSINT - No direct target contact")
    results.append("")

    # PHASE 1: DNS
    await context.bot.send_message(chat_id, "[1/12] DNS Deep Dive...")
    try:
        import dns.resolver
        dns_info = "=== [1] DNS RECORDS ===\n"
        for qtype in ['A', 'AAAA', 'MX', 'NS', 'TXT', 'SOA', 'CNAME', 'SRV', 'CAA']:
            try:
                answers = dns.resolver.resolve(target, qtype, lifetime=5, raise_on_no_answer=False)
                vals = [str(r) for r in answers]
                if vals:
                    dns_info += f"\n  {qtype} ({len(vals)}):\n"
                    for v in vals[:5]:
                        dns_info += f"    {v}\n"
                        # A record reverse DNS
                        if qtype == 'A':
                            try:
                                rev = dns.reversename.from_address(v)
                                ptr = dns.resolver.resolve(rev, 'PTR', lifetime=3)
                                dns_info += f"      PTR: {ptr[0]}\n"
                            except:
                                pass
            except:
                pass
        
        # MX provider detection
        dns_info += "\n  Mail Provider Analysis:\n"
        try:
            answers = dns.resolver.resolve(target, 'MX', lifetime=5)
            for rdata in answers:
                mx = str(rdata.exchange).lower()
                if 'google' in mx: dns_info += f"    {mx} => Google Workspace\n"
                elif 'outlook' in mx or 'protection.outlook' in mx: dns_info += f"    {mx} => Microsoft 365\n"
                elif 'mailgun' in mx: dns_info += f"    {mx} => Mailgun\n"
                elif 'sendgrid' in mx: dns_info += f"    {mx} => SendGrid\n"
                elif 'amazonaws' in mx or 'amazonses' in mx: dns_info += f"    {mx} => Amazon SES\n"
                elif 'zoho' in mx: dns_info += f"    {mx} => Zoho Mail\n"
                elif 'protonmail' in mx: dns_info += f"    {mx} => ProtonMail\n"
                else: dns_info += f"    {mx}\n"
        except:
            dns_info += "    No MX records\n"
        
        # Email Security
        dns_info += "\n  Email Security:\n"
        spf_found = False
        try:
            answers = dns.resolver.resolve(target, 'TXT', lifetime=5)
            for r in answers:
                if 'v=spf1' in str(r):
                    dns_info += f"    SPF: {str(r)[:180]}\n"
                    spf_found = True
                    break
        except:
            pass
        if not spf_found:
            dns_info += "    SPF: NOT CONFIGURED\n"
        
        try:
            answers = dns.resolver.resolve(f"_dmarc.{target}", 'TXT', lifetime=5)
            for r in answers:
                if 'v=DMARC1' in str(r):
                    dns_info += f"    DMARC: {str(r)[:180]}\n"
                    break
        except:
            dns_info += "    DMARC: NOT CONFIGURED\n"
        
        for sel in ['google', 'default', 'dkim', 'mail', 'selector1', 'protonmail']:
            try:
                dns.resolver.resolve(f"{sel}._domainkey.{target}", 'TXT', lifetime=3)
                dns_info += f"    DKIM ({sel}): Present\n"
            except:
                pass
        
        results.append(dns_info)
    except ImportError:
        results.append("=== [1] DNS ===\n  Install dnspython: pip install dnspython")
    except Exception as e:
        results.append(f"=== [1] DNS ===\n  Error: {str(e)}")

    # PHASE 2: WHOIS
    await context.bot.send_message(chat_id, "[2/12] WHOIS Lookup...")
    try:
        import whois
        w = whois.whois(target)
        whois_info = "=== [2] WHOIS ===\n"
        for label, key in [('Domain Status', 'status'), ('Registrar', 'registrar'),
                          ('Created', 'creation_date'), ('Updated', 'updated_date'),
                          ('Expires', 'expiration_date'), ('Registrant', 'name'),
                          ('Organization', 'org'), ('Country', 'country'),
                          ('City', 'city'), ('Phone', 'phone'), ('Email', 'email'),
                          ('Admin Email', 'admin_email'), ('Tech Email', 'tech_email')]:
            val = w.get(key)
            if val:
                if isinstance(val, list): val = val[0]
                whois_info += f"  {label}: {val}\n"
        ns = w.get('name_servers')
        if ns:
            if isinstance(ns, str): ns = [ns]
            whois_info += "\n  Name Servers:\n"
            for n in ns[:5]:
                whois_info += f"    {n}\n"
        results.append(whois_info)
    except:
        whois_info = await whois_socket_lookup(target, detailed=True)
        results.append(whois_info)

    # PHASE 3: SSL CERTIFICATE
    await context.bot.send_message(chat_id, "[3/12] SSL/TLS Certificate Analysis...")
    cert = get_certificate_info(target)
    if cert:
        cert_info = "=== [3] SSL/TLS CERTIFICATE ===\n"
        cert_info += f"  CN: {cert['cn']}\n  Org: {cert['org']}\n  Country: {cert['country']}\n"
        cert_info += f"  Issuer: {cert['issuer']}\n"
        cert_info += f"  Valid From: {cert['valid_from']}\n  Valid Until: {cert['valid_to']}\n"
        if cert['cipher']:
            cert_info += f"  Cipher: {cert['cipher'][0]}\n  Protocol: {cert['cipher'][1]}\n"
        cert_info += f"\n  SANs ({cert['sans_count']}):\n"
        for san in cert['sans'][:15]:
            cert_info += f"    {san}\n"
        if cert['sans_count'] > 15:
            cert_info += f"    ... and {cert['sans_count'] - 15} more\n"
        results.append(cert_info)
    else:
        results.append("=== [3] SSL/TLS ===\n  Cert info unavailable (port may be closed or no HTTPS)")

    # PHASE 4: SUBDOMAINS
    await context.bot.send_message(chat_id, "[4/12] Subdomain Enumeration (7 sources)...")
    subdomains = set()
    source_counts = {}
    
    sources = [
        ("crt.sh", f"https://crt.sh/?q=%25.{target}&output=json", lambda r: [n for e in r.json() for n in e.get('name_value', '').split('\n') if n and '*' not in n]),
        ("Hackertarget", f"https://api.hackertarget.com/hostsearch/?q={target}", lambda r: [l.split(',')[0].strip() for l in r.text.split('\n') if ',' in l]),
        ("AlienVault OTX", f"https://otx.alienvault.com/api/v1/indicators/domain/{target}/passive_dns", lambda r: [e.get('hostname', '') for e in r.json().get('passive_dns', []) if e.get('hostname')]),
        ("Anubis DB", f"https://jldc.me/anubis/subdomains/{target}", lambda r: r.json() if isinstance(r.json(), list) else []),
        ("Threatcrowd", f"https://www.threatcrowd.org/searchApi/v2/domain/report/?domain={target}", lambda r: r.json().get('subdomains', [])),
        ("Bufferover", f"https://dns.bufferover.run/dns?q=.{target}", lambda r: [p.split(',')[1].strip() for p in r.json().get('FDNS_A', []) if ',' in p]),
        ("RapidDNS", f"https://rapiddns.io/subdomain/{target}?full=1", lambda r: re.findall(r'[\w.-]+\.' + re.escape(target), r.text)),
    ]
    
    for name, url, parser in sources:
        try:
            r = requests.get(url, timeout=20, headers={"User-Agent": "Mozilla/5.0"})
            if r.status_code == 200:
                try:
                    items = parser(r)
                    count = 0
                    for item in items:
                        if isinstance(item, str):
                            sub = item.strip().lower()
                            if sub.endswith(target):
                                subdomains.add(sub)
                                count += 1
                    if count > 0:
                        source_counts[name] = count
                except:
                    pass
        except:
            pass
    
    if subdomains:
        sorted_subs = sorted(set(subdomains))
        sub_info = f"=== [4] SUBDOMAINS ({len(sorted_subs)} total) ===\n"
        sub_info += "\n  Sources:\n"
        for s, c in source_counts.items():
            sub_info += f"    {s}: {c}\n"
        
        # Categorize
        cats = {"Web": [], "API": [], "Admin": [], "Mail": [], "Dev/Test": [], "CDN/Static": [], "Monitoring": [], "Other": []}
        for sub in sorted_subs:
            p = sub.replace(f".{target}", "").lower()
            if p in ['www', '']: cats["Web"].append(sub)
            elif any(x in p for x in ['api', 'graphql', 'rest', 'gateway', 'backend']): cats["API"].append(sub)
            elif any(x in p for x in ['admin', 'manage', 'portal', 'dashboard', 'panel']): cats["Admin"].append(sub)
            elif any(x in p for x in ['mail', 'email', 'smtp', 'imap', 'webmail', 'owa', 'exchange']): cats["Mail"].append(sub)
            elif any(x in p for x in ['dev', 'stage', 'staging', 'test', 'beta', 'sandbox', 'qa', 'uat']): cats["Dev/Test"].append(sub)
            elif any(x in p for x in ['cdn', 'static', 'assets', 'img', 'css', 'js', 'media', 'files']): cats["CDN/Static"].append(sub)
            elif any(x in p for x in ['monitor', 'status', 'grafana', 'prometheus', 'nagios']): cats["Monitoring"].append(sub)
            else: cats["Other"].append(sub)
        
        for cat, subs in cats.items():
            if subs:
                sub_info += f"\n  [{cat}] ({len(subs)}):\n"
                for s in subs[:8]:
                    sub_info += f"    - {s}\n"
                if len(subs) > 8:
                    sub_info += f"    ... and {len(subs) - 8} more\n"
        results.append(sub_info)
    else:
        results.append("=== [4] Subdomains ===\n  None found from passive sources")

    # PHASE 5: IP & HOSTING INFO
    await context.bot.send_message(chat_id, "[5/12] IP & Hosting Intelligence...")
    host_info = "=== [5] IP & HOSTING ===\n"
    try:
        ip = socket.gethostbyname(target)
        host_info += f"  IP Address: {ip}\n"
        
        r = requests.get(f"https://ipapi.co/{ip}/json/", timeout=10, headers={"User-Agent": "Mozilla/5.0"})
        if r.status_code == 200:
            d = r.json()
            for k, v in [('IP', 'ip'), ('ISP/Org', 'org'), ('Country', 'country_name'),
                        ('Region', 'region'), ('City', 'city'), ('Postal', 'postal'),
                        ('Lat/Lon', 'latitude'), ('Timezone', 'timezone'), ('ASN', 'asn'),
                        ('Hosting', 'org_type')]:
                val = d.get(v)
                if val:
                    host_info += f"  {k}: {val}\n"
    except:
        host_info += "  Could not resolve or geolocate\n"
    
    # Check if on known cloud
    try:
        r = requests.get(f"https://api.hackertarget.com/aslookup/?q={ip}", timeout=10)
        if r.status_code == 200:
            host_info += f"\n  ASN Info:\n"
            for line in r.text.split('\n')[:5]:
                if line.strip():
                    host_info += f"    {line.strip()}\n"
    except:
        pass
    
    results.append(host_info)

    # PHASE 6: WEB TECH & WAF
    await context.bot.send_message(chat_id, "[6/12] Web Technology & WAF Detection...")
    
    for scheme in ["https", "http"]:
        try:
            r = requests.get(
                f"{scheme}://{target}", timeout=15,
                headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"},
                verify=False, allow_redirects=True
            )
            body = r.text
            hdrs = dict(r.headers)
            cookies = "; ".join([f"{c.name}={c.value}" for c in r.cookies])
            raw_hdrs = "\n".join([f"{k}: {v}" for k, v in r.headers.items()])
            
            # Full tech detection
            all_techs = detect_technologies(hdrs, body, cookies, target)
            all_wafs = detect_waf(hdrs, body, cookies, r.status_code)
            
            tech_section = f"=== [6] TECHNOLOGY STACK ({scheme.upper()}) ===\n"
            
            # Group by category
            cat_order = ["Web Server", "Cache", "Backend", "Framework", "CMS", "WP Theme", "WP Plugin",
                        "JS Framework", "Analytics", "CDN", "Security", "Other"]
            seen = set()
            for cat in cat_order:
                items = [(t[0], t[1], t[2]) for t in all_techs if t[0] == cat and t[1] not in seen]
                for item in items:
                    seen.add(item[1])
                if items:
                    tech_section += f"\n  {cat}:\n"
                    for _, name, conf in items:
                        tech_section += f"    {name} [{conf}]\n"
            
            # Failed categories
            uncat = [(t[0], t[1], t[2]) for t in all_techs if t[0] not in cat_order and t[1] not in seen]
            if uncat:
                tech_section += f"\n  Other:\n"
                for _, name, conf in uncat:
                    tech_section += f"    {name} [{conf}]\n"
            
            tech_section += f"\n  Response: {r.status_code} ({r.elapsed.total_seconds()*1000:.0f}ms)\n"
            tech_section += f"  Final URL: {r.url}\n"
            tech_section += f"  Title: {extract_title(body)}\n"
            tech_section += f"  Size: {len(body):,} bytes\n"
            
            results.append(tech_section)
            
            # WAF Section
            if all_wafs:
                waf_section = "=== [7] WAF / FIREWALL DETECTION ===\n"
                for waf in all_wafs:
                    waf_section += f"\n  {waf['name']} [{waf['confidence']}]\n"
                    for reason in waf['reasons'][:2]:
                        waf_section += f"    > {reason}\n"
                results.append(waf_section)
            else:
                results.append("=== [7] WAF / FIREWALL ===\n  No identifiable WAF detected")
            
            await context.bot.send_message(chat_id, "[7/12] WAF Analysis Complete")
            break
        except:
            continue
    else:
        results.append("=== [6] Technology ===\n  Could not connect to web server")
        results.append("=== [7] WAF ===\n  Could not check")

    # PHASE 8: WAYBACK MACHINE
    await context.bot.send_message(chat_id, "[8/12] Wayback Machine Archive Analysis...")
    try:
        r = requests.get(
            f"https://web.archive.org/cdx/search/cdx?url=*.{target}&output=json&fl=original,timestamp&limit=200&collapse=urlkey",
            timeout=25, headers={"User-Agent": "Mozilla/5.0"}
        )
        if r.status_code == 200 and len(r.json()) > 1:
            urls = sorted(set(e[0] for e in r.json()[1:] if e and len(e) > 0))
            wayb_info = f"=== [8] WAYBACK MACHINE ({len(urls)} unique URLs) ===\n"
            
            # Interesting endpoints
            interesting = [u for u in urls if any(x in u.lower() for x in 
                          ['api', 'admin', 'login', 'wp-admin', 'config', 'backup', '.git', '.env', 
                           'db', 'database', 'phpmyadmin', 'panel', 'dashboard', 'upload',
                           'includes', 'classes', 'vendor', 'node_modules', 'secret', 'key',
                           'password', 'credential', '.htaccess', 'config.php', 'wp-config'])]
            
            if interesting:
                wayb_info += f"\n  [!] Interesting endpoints ({len(interesting)}):\n"
                for u in interesting[:15]:
                    wayb_info += f"    {u}\n"
                if len(interesting) > 15:
                    wayb_info += f"    ... and {len(interesting) - 15} more\n"
            
            # Path categories
            exts = defaultdict(list)
            for u in urls:
                ext = u.split('.')[-1].split('?')[0].split('/')[0] if '.' in u.split('/')[-1] else 'no-ext'
                exts[ext].append(u)
            
            if 'php' in exts:
                wayb_info += f"\n  PHP pages: {len(exts['php'])}\n"
            if 'asp' in exts or 'aspx' in exts:
                wayb_info += f"  ASP.NET pages: {len(exts.get('asp', []) + exts.get('aspx', []))}\n"
            if 'js' in exts:
                wayb_info += f"  JavaScript files: {len(exts['js'])}\n"
            if 'json' in exts:
                wayb_info += f"  JSON APIs: {len(exts['json'])}\n"
            
            results.append(wayb_info)
        else:
            results.append("=== [8] Wayback ===\n  No historical data found")
    except Exception as e:
        results.append(f"=== [8] Wayback ===\n  Error: {str(e)}")

    # PHASE 9: EMAIL DISCOVERY
    await context.bot.send_message(chat_id, "[9/12] Email Discovery...")
    emails = set()
    
    # crt.sh
    try:
        r = requests.get(f"https://crt.sh/?q=%25.{target}&output=json", timeout=20,
                        headers={"User-Agent": "Mozilla/5.0"})
        if r.status_code == 200:
            for entry in r.json():
                for e in re.findall(r'[\w.+-]+@[\w-]+\.[\w.-]+', entry.get('name_value', '')):
                    emails.add(e.lower())
    except:
        pass
    
    # DNS TXT
    try:
        import dns.resolver
        answers = dns.resolver.resolve(target, 'TXT', lifetime=5)
        for rdata in answers:
            for e in re.findall(r'[\w.+-]+@[\w-]+\.[\w.-]+', str(rdata)):
                emails.add(e.lower())
    except:
        pass
    
    # Wayback
    try:
        r = requests.get(f"https://web.archive.org/cdx/search/cdx?url=*.{target}&output=json&fl=original,timestamp&limit=100",
                        timeout=15, headers={"User-Agent": "Mozilla/5.0"})
        if r.status_code == 200 and len(r.json()) > 1:
            for entry in r.json()[1:]:
                if entry and len(entry) > 0:
                    for e in re.findall(r'[\w.+-]+@[\w-]+\.[\w.-]+', entry[0]):
                        emails.add(e.lower())
    except:
        pass
    
    email_info = f"=== [9] EMAILS ({len(emails)} found) ===\n"
    if emails:
        internal = sorted([e for e in emails if e.endswith(f"@{target}") or target.split('.')[0] in e])
        external = sorted([e for e in emails if e not in internal])
        if internal:
            email_info += f"\n  [Internal to {target}]:\n"
            for e in internal[:10]:
                email_info += f"    {e}\n"
            if len(internal) > 10:
                email_info += f"    ... and {len(internal) - 10} more\n"
        if external:
            email_info += f"\n  [External/Related]:\n"
            for e in external[:8]:
                email_info += f"    {e}\n"
    else:
        email_info += "  No emails found\n"
    results.append(email_info)

    # PHASE 10: ROBOTS, SITEMAP, SECURITY.TXT
    await context.bot.send_message(chat_id, "[10/12] Robots, Sitemap & Security.txt...")
    extra = "=== [10] WEB FILES ===\n"
    
    files_to_check = [
        ("robots.txt", ["robots.txt"]),
        ("sitemap.xml", ["sitemap.xml"]),
        ("security.txt", [".well-known/security.txt", "security.txt"]),
        ("humans.txt", ["humans.txt"]),
        ("crossdomain.xml", ["crossdomain.xml"]),
        ("clientaccesspolicy.xml", ["clientaccesspolicy.xml"]),
    ]
    
    for label, paths in files_to_check:
        for path in paths:
            for scheme in ["https", "http"]:
                try:
                    r = requests.get(f"{scheme}://{target}/{path}", timeout=5,
                                    headers={"User-Agent": "Mozilla/5.0"}, verify=False)
                    if r.status_code == 200:
                        extra += f"\n  [{label}] FOUND at /{path}:\n"
                        if label == "robots.txt":
                            for line in r.text.split('\n')[:15]:
                                if line.strip() and not line.strip().startswith('#'):
                                    extra += f"    {line.strip()}\n"
                        elif label == "security.txt":
                            for line in r.text.split('\n')[:8]:
                                if line.strip():
                                    extra += f"    {line.strip()}\n"
                        else:
                            extra += f"    Size: {len(r.content)} bytes\n"
                        break
                except:
                    continue
    
    results.append(extra)

    # PHASE 11: HEADERS & SECURITY AUDIT
    await context.bot.send_message(chat_id, "[11/12] HTTP Headers & Security Audit...")
    sec_info = "=== [11] SECURITY HEADERS AUDIT ===\n"
    
    for scheme in ["https", "http"]:
        try:
            r = requests.get(f"{scheme}://{target}", timeout=10,
                            headers={"User-Agent": "Mozilla/5.0"}, verify=False)
            hdrs = r.headers
            
            important = {
                'Strict-Transport-Security': {'desc': 'HSTS - Force HTTPS', 'good': 'max-age='},
                'Content-Security-Policy': {'desc': 'CSP - XSS Protection', 'good': "script-src 'self'"},
                'X-Frame-Options': {'desc': 'Clickjacking Protection', 'good': 'DENY|SAMEORIGIN'},
                'X-Content-Type-Options': {'desc': 'MIME Sniffing Protection', 'good': 'nosniff'},
                'X-XSS-Protection': {'desc': 'XSS Filter', 'good': '1; mode=block'},
                'Referrer-Policy': {'desc': 'Referrer Leak Protection', 'good': 'same-origin|strict'},
                'Permissions-Policy': {'desc': 'Permissions Control', 'good': 'camera='},
                'Access-Control-Allow-Origin': {'desc': 'CORS Policy', 'good': 'self|null'},
                'Set-Cookie': {'desc': 'Cookie Security', 'good': 'HttpOnly|Secure|SameSite'},
                'X-Powered-By': {'desc': 'Information Disclosure', 'good': 'N/A (should be hidden)'},
                'Server': {'desc': 'Server Version Disclosure', 'good': 'N/A (should be generic)'},
            }
            
            sec_info += f"\n  {scheme.upper()}://{target}\n"
            sec_info += f"  {'='*40}\n"
            
            for hdr, info in important.items():
                hdr_low = hdr.lower()
                if hdr_low in {k.lower(): v for k, v in hdrs.items()}:
                    val = hdrs[hdr_low if hdr_low in {k.lower() for k in hdrs} else hdr]
                    status = "GOOD" if re.search(info['good'], val, re.I) else "EXISTS"
                    if hdr == 'X-Powered-By' or hdr == 'Server':
                        status = "WARNING (info disclosure)"
                    sec_info += f"  [{status}] {hdr}: {val[:80]}\n"
                else:
                    sec_info += f"  [MISSING] {hdr} - {info['desc']}\n"
            
            # Check for cookies
            if 'Set-Cookie' in hdrs:
                cookie_val = hdrs['Set-Cookie']
                issues = []
                if 'HttpOnly' not in cookie_val:
                    issues.append("No HttpOnly flag")
                if 'Secure' not in cookie_val:
                    issues.append("No Secure flag")
                if 'SameSite' not in cookie_val:
                    issues.append("No SameSite attribute")
                if issues:
                    sec_info += f"\n  [COOKIE ISSUES] {' | '.join(issues)}\n"
            
            break
        except:
            continue
    
    results.append(sec_info)

    # PHASE 12: ADDITIONAL OSINT
    await context.bot.send_message(chat_id, "[12/12] Additional OSINT...")
    extra2 = "=== [12] ADDITIONAL OSINT ===\n"
    
    # GitHub search (just check if org exists)
    try:
        org_name = target.split('.')[0]
        r = requests.get(f"https://api.github.com/orgs/{org_name}", timeout=8,
                        headers={"User-Agent": "Mozilla/5.0"})
        if r.status_code == 200:
            d = r.json()
            extra2 += f"\n  GitHub Organization: github.com/{org_name}\n"
            extra2 += f"    Name: {d.get('name', 'N/A')}\n"
            extra2 += f"    Public Repos: {d.get('public_repos', 'N/A')}\n"
            extra2 += f"    Members: {d.get('members_count', 'N/A')}\n"
    except:
        pass
    
    # Social checks
    social_checks = [
        f"twitter.com/{target.split('.')[0]}",
        f"linkedin.com/company/{target.split('.')[0]}",
        f"crunchbase.com/organization/{target.split('.')[0]}",
        f"angel.co/company/{target.split('.')[0]}",
    ]
    found_social = False
    for sc in social_checks:
        try:
            r = requests.get(f"https://{sc}", timeout=5,
                            headers={"User-Agent": "Mozilla/5.0"})
            if r.status_code < 400:
                extra2 += f"\n  Social/Profile: {sc}\n"
                found_social = True
        except:
            pass
    if not found_social:
        extra2 += "\n  No public social/professional profiles detected\n"
    
    # Technology count summary
    total_techs = len(set(t[1] for t in all_techs)) if 'all_techs' in dir() else 0
    extra2 += f"\n  Total Technologies Identified: ~{total_techs}\n"
    
    results.append(extra2)

    # SUMMARY
    elapsed = (datetime.now() - start_time).total_seconds()
    results.append("")
    results.append(f"{'='*60}")
    results.append(f"RECON COMPLETE in {elapsed:.1f} seconds")
    results.append(f"Target: {target}")
    results.append(f"Subdomains: {len(subdomains) if subdomains else 0}")
    results.append(f"Emails: {len(emails) if emails else 0}")
    results.append(f"Technologies: ~{total_techs}")
    
    await send_long_message(chat_id, context, "\n".join(results))
    await context.bot.send_message(chat_id, "✅ Ultra passive reconnaissance complete.")


# ======================== TELEGRAM HANDLERS ========================

async def start(update, context):
    if not is_authorized(update):
        return await update.message.reply_text("Unauthorized.")
    await update.message.reply_text(
        "🛡 ULTRA PASSIVE RECON BOT\n\n"
        "100% OSINT - No target contact\n\n"
        "/recon <domain> - Full passive recon (ALL phases)\n"
        "/help - Details\n\n"
        "12 phases: DNS, WHOIS, SSL, Subdomains, IP Geo,\n"
        "Web Tech, WAF, Wayback, Emails, Web Files,\n"
        "Security Audit, OSINT"
    )


async def help_cmd(update, context):
    if not is_authorized(update):
        return
    await update.message.reply_text(
        "/recon <domain> - Full passive recon\n\n"
        "Phases:\n"
        "[1] DNS - A, AAAA, MX, NS, TXT, SOA, SPF, DMARC, DKIM, SRV\n"
        "[2] WHOIS - Registrar, dates, contacts\n"
        "[3] SSL - Certificate, SANs, issuer, cipher\n"
        "[4] Subdomains - 7 sources, categorized\n"
        "[5] IP/Hosting - Geo, ISP, ASN\n"
        "[6] Tech Stack - Full fingerprinting\n"
        "[7] WAF Detection - 20+ signatures\n"
        "[8] Wayback - Historical URLs\n"
        "[9] Emails - Internal & external\n"
        "[10] Web Files - robots, sitemap, security.txt\n"
        "[11] Security Audit - Header analysis\n"
        "[12] OSINT - GitHub, social, summary\n\n"
        "Example: /recon example.com"
    )


async def recon_command(update, context):
    if not is_authorized(update):
        return await update.message.reply_text("Unauthorized.")
    if not context.args:
        return await update.message.reply_text("Usage: /recon <domain>")
    
    target = re.sub(r'^https?://', '', context.args[0].strip().lower()).split('/')[0].split('@')[-1]
    if not re.match(r'^[\w.-]+\.[a-zA-Z]{2,}$', target):
        return await update.message.reply_text(f"Invalid domain: {target}")
    
    await update.message.reply_text(f"🔍 Full passive recon on {target}...\n12 phases - I'll update you as each completes.")
    await passive_recon(target, update, context)


async def error_handler(update, context):
    print(f"Error: {context.error}")
    try:
        if update and update.effective_chat:
            await context.bot.send_message(update.effective_chat.id, f"Error: {str(context.error)[:150]}")
    except:
        pass


# ======================== AUTO-RESTART MAIN ========================

if __name__ == "__main__":
    if TELEGRAM_BOT_TOKEN == "YOUR_TELEGRAM_BOT_TOKEN_HERE":
        print("ERROR: Set your TELEGRAM_BOT_TOKEN in the script!")
        sys.exit(1)
    if YOUR_TELEGRAM_USER_ID == 123456789:
        print("WARNING: Set YOUR_TELEGRAM_USER_ID to restrict access!")
    
    max_retries = 999999
    retry_delay = 10
    attempt = 0
    
    while attempt < max_retries:
        attempt += 1
        try:
            print("=" * 50)
            print(f"Ultra Passive Recon Bot v3 - Run #{attempt}")
            print("Windows Compatible - 100% OSINT")
            print("Press Ctrl+C to stop permanently.")
            print("=" * 50)
            
            app = Application.builder().token(TELEGRAM_BOT_TOKEN).build()
            app.add_handler(CommandHandler("start", start))
            app.add_handler(CommandHandler("help", help_cmd))
            app.add_handler(CommandHandler("recon", recon_command))
            app.add_error_handler(error_handler)
            
            app.run_polling(allowed_updates=Update.ALL_TYPES)
            
        except KeyboardInterrupt:
            print("\nBot stopped by user.")
            sys.exit(0)
        except Exception as e:
            print(f"\nBot crashed: {e}")
            print(f"Restarting in {retry_delay}s...")
            time.sleep(retry_delay)